---
title: "nhp_reskit"
vignette: >
  %\VignetteIndexEntry{nhp_reskit}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---

An R package (just called `reskit`) that helps process NHP model results.


## Installation

You should be able to run the following R command to install {reskit}:

```r
# install.packages("pak") # if not already installed
pak::pak("The-Strategy-Unit/nhp_reskit")
```

On Windows, you may need to have [RTools](https://cloud.r-project.org/)
already installed in order to install reskit.

## Usage

As this package relies on [`{azkit}`][azk] for some of its functionality, you
will need certain environment variables to be available (see section below) in
order for these to work.

It is a good idea to check that your [azkit authentication][azkt] is set up
correctly before using this package.
Try:

```
az login
```

at your terminal, or

```r
azkit::get_auth_token()
```

to check these are running correctly.

### Examples of usage

Some key functions and workflows you might want to use include:


1. Use {azkit} to access an Azure data container, and read in all results
parquet files from a specific location on that container:

```r
# This assumes you have Azure authentication working, and the correct
# Azure endpoint variables in your environment.
# NB the file/data locations used here are invented examples.
# The best way to obtain a real results folder location is probably to read and
# filter a table of model runs metadata and extract the appropriate path
# variable; see `azkit::read_azure_table` for help with this.
data_container <- azkit::get_container("data_container")
results_location <- "results/dev/national/test"
results <- reskit::read_results_parquet_files(data_container, results_location)
```

This should return a named list of tibbles, stored as `results`, one for each
parquet file in the results location folder.

2. Re-using some of the variables above, you could instead retrieve data for
just some of the parquet files:

```r
# NB do not add the `.parquet` ext; just the basename of the file is required
selected_tables <- c("acuity", "default")

selected_results <- data_container |>
  reskit::read_results_parquet_files(results_location, selected_tables)
```

3. You can use your results list to support the creation of summary tables and
charts. For example:

```r
# generates a {gt} (HTML) table
reskit::compile_principal_pod_data(results) |>
  reskit::make_principal_pod_table()
```


See the "Plots and tables with reskit" vignette for more examples of things you
can do.



## Environment variables

To access Azure Storage you need to add some variables to a
[`.Renviron` file][posit_env] in your project.

⚠️These values are sensitive and should not be exposed to anyone outside The
Strategy Unit.
Make sure you include `.Renviron` in [the `.gitignore` file][github] for
your project.

Your `.Renviron` file should contain the variables below.
Ask a member of [the Data Science team][suds] for the necessary values.

```
AZ_STORAGE_EP=[your azure storage blob endpoint url]
```

For convenience, an example `.Renviron.example` file is provided in this
repository.
You can copy/save it, renamed to just `.Renviron`, to the root of any project
folder where you are using {reskit}.


## Adding reskit as a dependency in an R package

If you're developing an R package and you wish to use reskit functions,
here's how you can add it as a dependency, as it's not (yet) on CRAN.

In your `DESCRIPTION` file, you will need to add the following to a `Remotes`
section:

```dcf
Remotes:
    reskit=github::The-Strategy-Unit/nhp_reskit
```

The fiddly bit here is that the repo name is not the same as the package name.
So we have to specify the package using the `reskit=...` format.

As well as doing that, you still need to add reskit to the `Imports` section:

```dcf
Imports:
    reskit
```

As the package is in active development, you may wish to pin the dependency to
a specific version, using the `==` syntax, to avoid things breaking.

```dcf
Imports:
    reskit (== 1.1.0),
```

Or, you know, just YOLO it.


## Getting help

Please use the [Issues][issues] feature on GitHub to report any bugs, ideas
or problems, including with the package documentation.

Alternatively, to ask any questions about the package you may contact
[Fran Barton](mailto:francis.barton@nhs.net).

[azk]: https://the-strategy-unit.github.io/azkit/
[azkt]: https://the-strategy-unit.github.io/azkit/articles/troubleshooting.html
[posit_env]: https://docs.posit.co/ide/user/ide/guide/environments/r/managing-r.html#renviron
[github]: https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files
[suds]: https://the-strategy-unit.github.io/data_science/about.html
[issues]: https://github.com/The-Strategy-Unit/nhp_reskit/issues
